### ISSUE TITLE
Config port forwarding for clients

### ISSUE THREAD

**Issue by Jack-Meade** [Jack-Meade/BlackSphere#11]
Users should have to do the least amount of work to be able to set themselves up as the tracker/central server.
Enabling a way to port forward requests through their NAT would be advantageous, as it would be PlugAndPlay-esque.

**Comment by AlexSmith** [comment]
We have decided to close this issue due to the presumption that the user can port forward, Even though it would be a great help to automatically port forward, our research suggests that we would to use something like UPnP and in order for UPnP to have the power to auto port-forward there is a setting on most routers that might need to be enabled. So if the user is able to go into their router and enable UPnP the user should then be able to open a port. The port we wanted to auto open is port 22 and this port is believed to be open on more routers than routers believed to have UPnP enabled.

Thanks 
Alex
